name = "ai-token-billing"
main = "src/billing.ts"
compatibility_date = "2024-03-01"
[observability.logs]
enabled = true
invocation_logs = true

# CORS configuration (optional override)
[vars]
CORS_ORIGIN = "https://vibecode-82m.pages.dev"
ADMIN_KEY = "JIKA_KAMU_TAHU-jangan*bilang-$apa_sapa:yah"

# Binding KV Namespace (Ganti id dibawah ini dengan id KV Anda sendiri)
[[kv_namespaces]]
binding = "TOKEN_BALANCES"
id = "180dc2b7d8924ddd91c6a7b4b44ae4fa"
# preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID_HERE"